export const createRoomConstants = {
  CREATE_ROOM_START: "CREATE_ROOM_START",
  CREATE_ROOM_LOADING: "CREATE_ROOM_LOADING",
  CREATE_ROOM_SUCCESS: "CREATE_ROOM_SUCCESS",
  CREATE_ROOM_ERROR: "CREATE_ROOM_ERROR"
}